version: '3.8'

services:
   app:
     image: basay/amtel:latest
     container_name: app_amtel
     command: uvicorn main:app --host 0.0.0.0 --port 8000
     networks:
       - amtelnet
     volumes:
       - .:/app
     ports:
       - "8000:8000"
     depends_on:
       db:
         condition: service_started
     environment:
       - POSTGRES_USER=root
       - POSTGRES_PASSWORD=example
       - POSTGRES_DB=test_db


   db:
     image: postgres:latest
     container_name: db_amtel
     restart: always
     hostname: db
     networks:
       - amtelnet
     volumes:
       - ./database:/lib/var/postgresql/data
     ports:
       - "8081:5432"
     environment:
       POSTGRES_USER: root
       POSTGRES_PASSWORD: example
       POSTGRES_DB: test_db
     healthcheck:
        test: ["CMD-SHELL", "pg_isready", "--quiet"]
        interval: 5s
        timeout: 5s
networks:
  amtelnet:
     driver: bridge