
version: '3.8'

services:
   app:
     build: .
     image: basay/amtel:latest
     command: uvicorn main:app --host 0.0.0.0 --port 8000
     networks:
       - amtelnet
     volumes:
       - .:/app
     ports:
       - "8000:8000"
     depends_on:
       - postgres
     environment:
       - POSTGRES_USER=root
       - POSTGRES_PASSWORD=example
       - POSTGRES_DB=test_db


   postgres:
     image: postgres:latest
     restart: always
     hostname: postgres
     networks:
       - amtelnet
     volumes:
       - ./database:/lib/var/postgresql/data
     ports:
       - "8081:5432"
     environment:
       POSTGRES_USER: root
       POSTGRES_PASSWORD: example
       POSTGRES_DB: test_db
networks:
  amtelnet:
     name: amtel
